(function outer(modules, cache, entries){

  /**
   * Global
   */

  var global = (function(){ return this; })();

  /**
   * Require `name`.
   *
   * @param {String} name
   * @api public
   */

  function require(name){
    if (cache[name]) return cache[name].exports;
    if (modules[name]) return call(name, require);
    throw new Error('cannot find module "' + name + '"');
  }

  /**
   * Call module `id` and cache it.
   *
   * @param {Number} id
   * @param {Function} require
   * @return {Function}
   * @api private
   */

  function call(id, require){
    var m = cache[id] = { exports: {} };
    var mod = modules[id];
    var name = mod[2];
    var fn = mod[0];
    var threw = true;

    try {
      fn.call(m.exports, function(req){
        var dep = modules[id][1][req];
        return require(dep || req);
      }, m, m.exports, outer, modules, cache, entries);
      threw = false;
    } finally {
      if (threw) {
        delete cache[id];
      } else if (name) {
        // expose as 'name'.
        cache[name] = cache[id];
      }
    }

    return cache[id].exports;
  }

  /**
   * Require all entries exposing them on global if needed.
   */

  for (var id in entries) {
    if (entries[id]) {
      global[entries[id]] = require(id);
    } else {
      require(id);
    }
  }

  /**
   * Duo flag.
   */

  require.duo = true;

  /**
   * Expose cache.
   */

  require.cache = cache;

  /**
   * Expose modules
   */

  require.modules = modules;

  /**
   * Return newest require.
   */

   return require;
})({
1: [function(require, module, exports) {
// main

let server = 'http://localhost:3002';
// var server = 'http://sa.diglossa.org:3002';

chrome.runtime.onMessage.addListener(function(message, sender, sendResponse) {
    let query = [server, '/', 'morph?form=', message.form, '&', 'next=', message.next].join('');
    let xhr = new XMLHttpRequest();
    xhr.open("GET", query, true);
    xhr.onreadystatechange = function() {
        if (xhr.readyState == 4) {
            // FIXME:
            let res = {query: message.form};
            if (xhr.responseText) res = JSON.parse(xhr.responseText);
            let data = require('./tmp.js');
            res.data = data[0];

            res.target = message.target;
            // console.log('MESSAGE');
            chrome.tabs.query({active: true, currentWindow: true}, function(tabs){
                chrome.tabs.sendMessage(tabs[0].id, {action: "morph_result", res: res, target: message.target}, function(response) {});
                data = null;
            });
        }
    };
    xhr.send();
    return true;
});

// function log() { console.log.apply(console, arguments); }

}, {"./tmp.js":2}],
2: [function(require, module, exports) {
//

let data = [
        {"f":["kodayati"],
         "v":"kudf!",
         "s":"tip",
         "n":"10.0008",
         "p":"u",
         "l":"law",
         "d":[{"r":"1.3.1", "i":["kudf!"]},
              {"r":"1.3.2", "i":["kudf!"]},
              {"r":"1.3.9", "i":["kud"]},
              {"r":"3.4.69", "i":["kud"]},
              {"r":"3.2.123", "i":["kud+la!w"]},
              {"r":"3.4.77", "i":["kud+la!w"]},
              {"r":"1.3.3", "i":["kud+la!w"]},
              {"r":"1.3.9", "i":["kud+la!"]},
              {"r":"1.3.2", "i":["kud+la!"]},
              {"r":"1.3.9", "i":["kud+l"]},
              {"r":"3.4.78", "i":["kud+tip"]},
              {"r":"1.4.99", "i":["kud+tip"]},
              {"r":"1.4.101", "i":["kud+tip"]},
              {"r":"1.4.102", "i":["kud+tip"]},
              {"r":"1.4.108", "i":["kud+tip"]},
              {"r":"3.4.113", "i":["kud+tip"]},
              {"r":"3.1.25", "i":["kud+Ric+tip"]},
              {"r":"3.1.68", "i":["kud+Ric+Sap+tip"]},
              {"r":"3.4.113", "i":["kud+Ric+Sap+tip"]},
              {"r":"1.3.8", "i":["kud+Ric+Sap+tip"]},
              {"r":"1.3.3", "i":["kud+Ric+Sap+tip"]},
              {"r":"1.3.7", "i":["kud+Ric+Sap+tip"]},
              {"r":"1.3.9", "i":["kud+i+a+tip"]},
              {"r":"7.3.86", "i":["kodi+a+tip"]},
              {"r":"7.3.84", "i":["kode+a+tip"]},
              {"r":"1.3.3", "i":["kode+a+tip"]},
              {"r":"1.3.9", "i":["kode+a+ti"]},
              {"r":"6.1.78", "i":["koday+a+ti"]},
              {"r":"~2", "i":["kodayati"]}]},
        {"f":["kodayataH"],
         "v":"kudf!",
         "s":"tas",
         "n":"10.0008",
         "p":"u",
         "l":"law",
         "d":[{"r":"1.3.1", "i":["kudf!"]},
              {"r":"1.3.2", "i":["kudf!"]},
              {"r":"1.3.9", "i":["kud"]},
              {"r":"3.1.32", "i":["kud"]},
              {"r":"3.4.69", "i":["kud"]},
              {"r":"3.2.123", "i":["kud+la!w"]},
              {"r":"3.4.77", "i":["kud+la!w"]},
              {"r":"1.3.3", "i":["kud+la!w"]},
              {"r":"1.3.9", "i":["kud+la!"]},
              {"r":"1.3.2", "i":["kud+la!"]},
              {"r":"1.3.9", "i":["kud+l"]},
              {"r":"3.4.78", "i":["kud+tas"]},
              {"r":"1.4.99", "i":["kud+tas"]},
              {"r":"1.4.101", "i":["kud+tas"]},
              {"r":"1.4.102", "i":["kud+tas"]},
              {"r":"1.4.108", "i":["kud+tas"]},
              {"r":"3.4.113", "i":["kud+tas"]},
              {"r":"3.1.25", "i":["kud+Ric+Ric+tas"]},
              {"r":"3.1.68", "i":["kud+Ric+Sap+tas"]},
              {"r":"3.4.113", "i":["kud+Ric+Sap+tas"]},
              {"r":"1.3.8", "i":["kud+Ric+Sap+tas"]},
              {"r":"1.3.3", "i":["kud+Ric+Sap+tas"]},
              {"r":"1.3.7", "i":["kud+Ric+Sap+tas"]},
              {"r":"1.3.9", "i":["kud+i+a+tas"]},
              {"r":"7.3.86", "i":["kodi+a+tas"]},
              {"r":"7.3.84", "i":["kode+a+tas"]},
              {"r":"1.3.4", "i":["kode+a+tas"]},
              {"r":"6.1.78", "i":["koday+a+tas"]},
              {"r":"8.2.66", "i":["kodaya+tar@"]},
              {"r":"1.3.2", "i":["kodaya+tar@"]},
              {"r":"1.3.9", "i":["kodaya+tar"]},
              {"r":"8.3.15", "i":["kodaya+taH"]},
              {"r":"~2", "i":["kodayataH"]}]},
        {"f":["kodayanti"],
         "v":"kudf!",
         "s":"Ji",
         "n":"10.0008",
         "p":"u",
         "l":"law",
         "d":[{"r":"1.3.1", "i":["kudf!"]},
              {"r":"1.3.2", "i":["kudf!"]},
              {"r":"1.3.9", "i":["kud"]},
              {"r":"3.1.32", "i":["kud"]},
              {"r":"3.4.69", "i":["kud"]},
              {"r":"3.2.123", "i":["kud+la!w"]},
              {"r":"3.4.77", "i":["kud+la!w"]},
              {"r":"1.3.3", "i":["kud+la!w"]},
              {"r":"1.3.9", "i":["kud+la!"]},
              {"r":"1.3.2", "i":["kud+la!"]},
              {"r":"1.3.9", "i":["kud+l"]},
              {"r":"3.4.78", "i":["kud+Ji"]},
              {"r":"1.4.99", "i":["kud+Ji"]},
              {"r":"1.4.101", "i":["kud+Ji"]},
              {"r":"1.4.102", "i":["kud+Ji"]},
              {"r":"1.4.108", "i":["kud+Ji"]},
              {"r":"3.4.113", "i":["kud+Ji"]},
              {"r":"3.1.25", "i":["kud+Ric+Ji"]},
              {"r":"3.1.68", "i":["kud+Ric+Sap+Ji"]},
              {"r":"3.4.113", "i":["kud+Ric+Sap+Ji"]},
              {"r":"1.3.8", "i":["kud+Ric+Sap+Ji"]},
              {"r":"1.3.3", "i":["kud+Ric+Sap+Ji"]},
              {"r":"1.3.7", "i":["kud+Ric+Sap+Ji"]},
              {"r":"1.3.9", "i":["kud+i+a+Ji"]},
              {"r":"7.3.86", "i":["kodi+a+Ji"]},
              {"r":"7.3.84", "i":["kode+a+Ji"]},
              {"r":"7.1.3", "i":["kode+a+anti"]},
              {"r":"6.1.78", "i":["koday+a+anti"]},
              {"r":"6.1.97", "i":["koday+anti"]},
              {"r":"8.3.24", "i":["koday+aMti"]},
              {"r":"8.4.58", "i":["kodayanti"]},
              {"r":"~2", "i":["kodayanti"]}]},
        {"f":["kodayasi"],
         "v":"kudf!",
         "s":"sip",
         "n":"10.0008",
         "p":"u",
         "l":"law",
         "d":[{"r":"1.3.1", "i":["kudf!"]},
              {"r":"1.3.2", "i":["kudf!"]},
              {"r":"1.3.9", "i":["kud"]},
              {"r":"3.1.32", "i":["kud"]},
              {"r":"3.4.69", "i":["kud"]},
              {"r":"3.2.123", "i":["kud+la!w"]},
              {"r":"3.4.77", "i":["kud+la!w"]},
              {"r":"1.3.3", "i":["kud+la!w"]},
              {"r":"1.3.9", "i":["kud+la!"]},
              {"r":"1.3.2", "i":["kud+la!"]},
              {"r":"1.3.9", "i":["kud+l"]},
              {"r":"3.4.78", "i":["kud+sip"]},
              {"r":"1.4.99", "i":["kud+sip"]},
              {"r":"1.4.101", "i":["kud+sip"]},
              {"r":"1.4.102", "i":["kud+sip"]},
              {"r":"1.4.105", "i":["kud+sip"]},
              {"r":"3.4.113", "i":["kud+sip"]},
              {"r":"3.1.25", "i":["kud+Ric+sip"]},
              {"r":"3.1.68", "i":["kud+Ric+Sap+sip"]},
              {"r":"3.4.113", "i":["kud+Ric+Sap+sip"]},
              {"r":"1.3.8", "i":["kud+Ric+Sap+sip"]},
              {"r":"1.3.3", "i":["kud+Ric+Sap+sip"]},
              {"r":"1.3.7", "i":["kud+Ric+Sap+sip"]},
              {"r":"1.3.9", "i":["kud+i+a+sip"]},
              {"r":"7.3.86", "i":["kodi+a+sip"]},
              {"r":"7.3.84", "i":["kode+a+sip"]},
              {"r":"1.3.3", "i":["kode+a+sip"]},
              {"r":"1.3.9", "i":["kode+a+si"]},
              {"r":"6.1.78", "i":["koday+a+si"]},
              {"r":"~2", "i":["kodayasi"]}]},
        {"f":["kodayaTaH"],
         "v":"kudf!",
         "s":"Tas",
         "n":"10.0008",
         "p":"u",
         "l":"law",
         "d":[{"r":"1.3.1", "i":["kudf!"]},
              {"r":"1.3.2", "i":["kudf!"]},
              {"r":"1.3.9", "i":["kud"]},
              {"r":"3.1.32", "i":["kud"]},
              {"r":"3.4.69", "i":["kud"]},
              {"r":"3.2.123", "i":["kud+la!w"]},
              {"r":"3.4.77", "i":["kud+la!w"]},
              {"r":"1.3.3", "i":["kud+la!w"]},
              {"r":"1.3.9", "i":["kud+la!"]},
              {"r":"1.3.2", "i":["kud+la!"]},
              {"r":"1.3.9", "i":["kud+l"]},
              {"r":"3.4.78", "i":["kud+Tas"]},
              {"r":"1.4.99", "i":["kud+Tas"]},
              {"r":"1.4.101", "i":["kud+Tas"]},
              {"r":"1.4.102", "i":["kud+Tas"]},
              {"r":"1.4.105", "i":["kud+Tas"]},
              {"r":"3.4.113", "i":["kud+Tas"]},
              {"r":"3.1.25", "i":["kud+Ric+Ric+Tas"]},
              {"r":"3.1.68", "i":["kud+Ric+Sap+Tas"]},
              {"r":"3.4.113", "i":["kud+Ric+Sap+Tas"]},
              {"r":"1.3.8", "i":["kud+Ric+Sap+Tas"]},
              {"r":"1.3.3", "i":["kud+Ric+Sap+Tas"]},
              {"r":"1.3.7", "i":["kud+Ric+Sap+Tas"]},
              {"r":"1.3.9", "i":["kud+i+a+Tas"]},
              {"r":"7.3.86", "i":["kodi+a+Tas"]},
              {"r":"7.3.84", "i":["kode+a+Tas"]},
              {"r":"1.3.4", "i":["kode+a+Tas"]},
              {"r":"6.1.78", "i":["koday+a+Tas"]},
              {"r":"8.2.66", "i":["kodaya+Tar@"]},
              {"r":"1.3.2", "i":["kodaya+Tar@"]},
              {"r":"1.3.9", "i":["kodaya+Tar"]},
              {"r":"8.3.15", "i":["kodaya+TaH"]},
              {"r":"~2", "i":["kodayaTaH"]}]},
        {"f":["kodayaTa"],
         "v":"kudf!",
         "s":"Ta",
         "n":"10.0008",
         "p":"u",
         "l":"law",
         "d":[{"r":"1.3.1", "i":["kudf!"]},
              {"r":"1.3.2", "i":["kudf!"]},
              {"r":"1.3.9", "i":["kud"]},
              {"r":"3.1.32", "i":["kud"]},
              {"r":"3.4.69", "i":["kud"]},
              {"r":"3.2.123", "i":["kud+la!w"]},
              {"r":"3.4.77", "i":["kud+la!w"]},
              {"r":"1.3.3", "i":["kud+la!w"]},
              {"r":"1.3.9", "i":["kud+la!"]},
              {"r":"1.3.2", "i":["kud+la!"]},
              {"r":"1.3.9", "i":["kud+l"]},
              {"r":"3.4.78", "i":["kud+Ta"]},
              {"r":"1.4.99", "i":["kud+Ta"]},
              {"r":"1.4.101", "i":["kud+Ta"]},
              {"r":"1.4.102", "i":["kud+Ta"]},
              {"r":"1.4.105", "i":["kud+Ta"]},
              {"r":"3.4.113", "i":["kud+Ta"]},
              {"r":"3.1.25", "i":["kud+Ric+Ta"]},
              {"r":"3.1.68", "i":["kud+Ric+Sap+Ta"]},
              {"r":"3.4.113", "i":["kud+Ric+Sap+Ta"]},
              {"r":"1.3.8", "i":["kud+Ric+Sap+Ta"]},
              {"r":"1.3.3", "i":["kud+Ric+Sap+Ta"]},
              {"r":"1.3.7", "i":["kud+Ric+Sap+Ta"]},
              {"r":"1.3.9", "i":["kud+i+a+Ta"]},
              {"r":"7.3.86", "i":["kodi+a+Ta"]},
              {"r":"7.3.84", "i":["kode+a+Ta"]},
              {"r":"6.1.78", "i":["koday+a+Ta"]},
              {"r":"~2", "i":["kodayaTa"]}]},
        {"f":["kodayAmi"],
         "v":"kudf!",
         "s":"mip",
         "n":"10.0008",
         "p":"u",
         "l":"law",
         "d":[{"r":"1.3.1", "i":["kudf!"]},
              {"r":"1.3.2", "i":["kudf!"]},
              {"r":"1.3.9", "i":["kud"]},
              {"r":"3.1.32", "i":["kud"]},
              {"r":"3.4.69", "i":["kud"]},
              {"r":"3.2.123", "i":["kud+la!w"]},
              {"r":"3.4.77", "i":["kud+la!w"]},
              {"r":"1.3.3", "i":["kud+la!w"]},
              {"r":"1.3.9", "i":["kud+la!"]},
              {"r":"1.3.2", "i":["kud+la!"]},
              {"r":"1.3.9", "i":["kud+l"]},
              {"r":"3.4.78", "i":["kud+mip"]},
              {"r":"1.4.99", "i":["kud+mip"]},
              {"r":"1.4.101", "i":["kud+mip"]},
              {"r":"1.4.102", "i":["kud+mip"]},
              {"r":"1.4.107", "i":["kud+mip"]},
              {"r":"3.4.113", "i":["kud+mip"]},
              {"r":"3.1.25", "i":["kud+Ric+mip"]},
              {"r":"3.1.68", "i":["kud+Ric+Sap+mip"]},
              {"r":"3.4.113", "i":["kud+Ric+Sap+mip"]},
              {"r":"1.3.8", "i":["kud+Ric+Sap+mip"]},
              {"r":"1.3.3", "i":["kud+Ric+Sap+mip"]},
              {"r":"1.3.7", "i":["kud+Ric+Sap+mip"]},
              {"r":"1.3.9", "i":["kud+i+a+mip"]},
              {"r":"7.3.86", "i":["kodi+a+mip"]},
              {"r":"7.3.84", "i":["kode+a+mip"]},
              {"r":"1.3.3", "i":["kode+a+mip"]},
              {"r":"1.3.9", "i":["kode+a+mi"]},
              {"r":"6.1.78", "i":["koday+a+mi"]},
              {"r":"7.3.101", "i":["kodayA+mi"]},
              {"r":"~2", "i":["kodayAmi"]}]},
        {"f":["kodayAvaH"],
         "v":"kudf!",
         "s":"vas",
         "n":"10.0008",
         "p":"u",
         "l":"law",
         "d":[{"r":"1.3.1", "i":["kudf!"]},
              {"r":"1.3.2", "i":["kudf!"]},
              {"r":"1.3.9", "i":["kud"]},
              {"r":"3.1.32", "i":["kud"]},
              {"r":"3.4.69", "i":["kud"]},
              {"r":"3.2.123", "i":["kud+la!w"]},
              {"r":"3.4.77", "i":["kud+la!w"]},
              {"r":"1.3.3", "i":["kud+la!w"]},
              {"r":"1.3.9", "i":["kud+la!"]},
              {"r":"1.3.2", "i":["kud+la!"]},
              {"r":"1.3.9", "i":["kud+l"]},
              {"r":"3.4.78", "i":["kud+vas"]},
              {"r":"1.4.99", "i":["kud+vas"]},
              {"r":"1.4.101", "i":["kud+vas"]},
              {"r":"1.4.102", "i":["kud+vas"]},
              {"r":"1.4.107", "i":["kud+vas"]},
              {"r":"3.4.113", "i":["kud+vas"]},
              {"r":"3.1.25", "i":["kud+Ric+vas"]},
              {"r":"3.1.68", "i":["kud+Ric+Sap+vas"]},
              {"r":"3.4.113", "i":["kud+Ric+Sap+vas"]},
              {"r":"1.3.8", "i":["kud+Ric+Sap+vas"]},
              {"r":"1.3.3", "i":["kud+Ric+Sap+vas"]},
              {"r":"1.3.7", "i":["kud+Ric+Sap+vas"]},
              {"r":"1.3.9", "i":["kud+i+a+vas"]},
              {"r":"7.3.86", "i":["kodi+a+vas"]},
              {"r":"7.3.84", "i":["kode+a+vas"]},
              {"r":"1.3.4", "i":["kode+a+vas"]},
              {"r":"6.1.78", "i":["koday+a+vas"]},
              {"r":"7.3.101", "i":["kodayA+vas"]},
              {"r":"8.2.66", "i":["kodayA+var@"]},
              {"r":"1.3.2", "i":["kodayA+var@"]},
              {"r":"1.3.9", "i":["kodayA+var"]},
              {"r":"8.3.15", "i":["kodayA+vaH"]},
              {"r":"~2", "i":["kodayAvaH"]}]},
        {"f":["kodayAmaH"],
         "v":"kudf!",
         "s":"mas",
         "n":"10.0008",
         "p":"u",
         "l":"law",
         "d":[{"r":"1.3.1", "i":["kudf!"]},
              {"r":"1.3.2", "i":["kudf!"]},
              {"r":"1.3.9", "i":["kud"]},
              {"r":"3.1.32", "i":["kud"]},
              {"r":"3.4.69", "i":["kud"]},
              {"r":"3.2.123", "i":["kud+la!w"]},
              {"r":"3.4.77", "i":["kud+la!w"]},
              {"r":"1.3.3", "i":["kud+la!w"]},
              {"r":"1.3.9", "i":["kud+la!"]},
              {"r":"1.3.2", "i":["kud+la!"]},
              {"r":"1.3.9", "i":["kud+l"]},
              {"r":"3.4.78", "i":["kud+mas"]},
              {"r":"1.4.99", "i":["kud+mas"]},
              {"r":"1.4.101", "i":["kud+mas"]},
              {"r":"1.4.102", "i":["kud+mas"]},
              {"r":"1.4.107", "i":["kud+mas"]},
              {"r":"3.4.113", "i":["kud+mas"]},
              {"r":"3.1.25", "i":["kud+Ric+mas"]},
              {"r":"3.1.68", "i":["kud+Ric+Sap+mas"]},
              {"r":"3.4.113", "i":["kud+Ric+Sap+mas"]},
              {"r":"1.3.8", "i":["kud+Ric+Sap+mas"]},
              {"r":"1.3.3", "i":["kud+Ric+Sap+mas"]},
              {"r":"1.3.7", "i":["kud+Ric+Sap+mas"]},
              {"r":"1.3.9", "i":["kud+i+a+mas"]},
              {"r":"7.3.86", "i":["kodi+a+mas"]},
              {"r":"7.3.84", "i":["kode+a+mas"]},
              {"r":"1.3.4", "i":["kode+a+mas"]},
              {"r":"6.1.78", "i":["koday+a+mas"]},
              {"r":"7.3.101", "i":["kodayA+mas"]},
              {"r":"8.2.66", "i":["kodayA+mar@"]},
              {"r":"1.3.2", "i":["kodayA+mar@"]},
              {"r":"1.3.9", "i":["kodayA+mar"]},
              {"r":"8.3.15", "i":["kodayA+maH"]},
              {"r":"~2", "i":["kodayAmaH"]}]},
        {"f":["kodayate"],
         "v":"kudf!",
         "s":"ta",
         "n":"10.0008",
         "p":"u",
         "l":"law",
         "d":[{"r":"1.3.1", "i":["kudf!"]},
              {"r":"1.3.2", "i":["kudf!"]},
              {"r":"1.3.9", "i":["kud"]},
              {"r":"3.1.32", "i":["kud"]},
              {"r":"3.4.69", "i":["kud"]},
              {"r":"3.2.123", "i":["kud+la!w"]},
              {"r":"3.4.77", "i":["kud+la!w"]},
              {"r":"1.3.3", "i":["kud+la!w"]},
              {"r":"1.3.9", "i":["kud+la!"]},
              {"r":"1.3.2", "i":["kud+la!"]},
              {"r":"1.3.9", "i":["kud+l"]},
              {"r":"3.4.78", "i":["kud+ta"]},
              {"r":"1.4.100", "i":["kud+ta"]},
              {"r":"1.4.101", "i":["kud+ta"]},
              {"r":"1.4.102", "i":["kud+ta"]},
              {"r":"1.4.108", "i":["kud+ta"]},
              {"r":"3.4.113", "i":["kud+ta"]},
              {"r":"3.1.25", "i":["kud+Ric+ta"]},
              {"r":"3.1.68", "i":["kud+Ric+Sap+ta"]},
              {"r":"3.4.113", "i":["kud+Ric+Sap+ta"]},
              {"r":"1.3.8", "i":["kud+Ric+Sap+ta"]},
              {"r":"1.3.3", "i":["kud+Ric+Sap+ta"]},
              {"r":"1.3.7", "i":["kud+Ric+Sap+ta"]},
              {"r":"1.3.9", "i":["kud+i+a+ta"]},
              {"r":"7.3.86", "i":["kodi+a+ta"]},
              {"r":"3.4.79", "i":["kodi+a+te"]},
              {"r":"7.3.84", "i":["kode+a+te"]},
              {"r":"6.1.78", "i":["koday+a+te"]},
              {"r":"~2", "i":["kodayate"]}]},
        {"f":["kodayete"],
         "v":"kudf!",
         "s":"AtAm",
         "n":"10.0008",
         "p":"u",
         "l":"law",
         "d":[{"r":"1.3.1", "i":["kudf!"]},
              {"r":"1.3.2", "i":["kudf!"]},
              {"r":"1.3.9", "i":["kud"]},
              {"r":"3.1.32", "i":["kud"]},
              {"r":"3.4.69", "i":["kud"]},
              {"r":"3.2.123", "i":["kud+la!w"]},
              {"r":"3.4.77", "i":["kud+la!w"]},
              {"r":"1.3.3", "i":["kud+la!w"]},
              {"r":"1.3.9", "i":["kud+la!"]},
              {"r":"1.3.2", "i":["kud+la!"]},
              {"r":"1.3.9", "i":["kud+l"]},
              {"r":"3.4.78", "i":["kud+AtAm"]},
              {"r":"1.4.100", "i":["kud+AtAm"]},
              {"r":"1.4.101", "i":["kud+AtAm"]},
              {"r":"1.4.102", "i":["kud+AtAm"]},
              {"r":"1.4.108", "i":["kud+AtAm"]},
              {"r":"3.4.113", "i":["kud+AtAm"]},
              {"r":"3.1.25", "i":["kud+Ric+AtAm"]},
              {"r":"3.1.68", "i":["kud+Ric+Sap+AtAm"]},
              {"r":"3.4.113", "i":["kud+Ric+Sap+AtAm"]},
              {"r":"1.3.8", "i":["kud+Ric+Sap+AtAm"]},
              {"r":"1.3.3", "i":["kud+Ric+Sap+AtAm"]},
              {"r":"1.3.7", "i":["kud+Ric+Sap+AtAm"]},
              {"r":"1.3.9", "i":["kud+i+a+AtAm"]},
              {"r":"7.3.86", "i":["kodi+a+AtAm"]},
              {"r":"1.3.4", "i":["kodi+a+AtAm"]},
              {"r":"3.4.79", "i":["kodi+a+Ate"]},
              {"r":"7.2.81", "i":["kodi+a+iy+te"]},
              {"r":"7.3.84", "i":["kode+a+iy+te"]},
              {"r":"6.1.78", "i":["koday+a+iy+te"]},
              {"r":"6.1.66", "i":["koday+a+i+te"]},
              {"r":"6.1.87", "i":["koday+ete"]},
              {"r":"~2", "i":["kodayete"]}]},
        {"f":["kodayante"],
         "v":"kudf!",
         "s":"Ja",
         "n":"10.0008",
         "p":"u",
         "l":"law",
         "d":[{"r":"1.3.1", "i":["kudf!"]},
              {"r":"1.3.2", "i":["kudf!"]},
              {"r":"1.3.9", "i":["kud"]},
              {"r":"3.1.32", "i":["kud"]},
              {"r":"3.4.69", "i":["kud"]},
              {"r":"3.2.123", "i":["kud+la!w"]},
              {"r":"3.4.77", "i":["kud+la!w"]},
              {"r":"1.3.3", "i":["kud+la!w"]},
              {"r":"1.3.9", "i":["kud+la!"]},
              {"r":"1.3.2", "i":["kud+la!"]},
              {"r":"1.3.9", "i":["kud+l"]},
              {"r":"3.4.78", "i":["kud+Ja"]},
              {"r":"1.4.100", "i":["kud+Ja"]},
              {"r":"1.4.101", "i":["kud+Ja"]},
              {"r":"1.4.102", "i":["kud+Ja"]},
              {"r":"1.4.108", "i":["kud+Ja"]},
              {"r":"3.4.113", "i":["kud+Ja"]},
              {"r":"3.1.25", "i":["kud+Ric+Ja"]},
              {"r":"3.1.68", "i":["kud+Ric+Sap+Ja"]},
              {"r":"3.4.113", "i":["kud+Ric+Sap+Ja"]},
              {"r":"1.3.8", "i":["kud+Ric+Sap+Ja"]},
              {"r":"1.3.3", "i":["kud+Ric+Sap+Ja"]},
              {"r":"1.3.7", "i":["kud+Ric+Sap+Ja"]},
              {"r":"1.3.9", "i":["kud+i+a+Ja"]},
              {"r":"7.3.86", "i":["kodi+a+Ja"]},
              {"r":"7.1.3", "i":["kodi+a+anta"]},
              {"r":"3.4.79", "i":["kodi+a+ante"]},
              {"r":"7.3.84", "i":["kode+a+ante"]},
              {"r":"6.1.78", "i":["koday+a+ante"]},
              {"r":"6.1.97", "i":["koday+ante"]},
              {"r":"8.3.24", "i":["koday+aMte"]},
              {"r":"8.4.58", "i":["kodayante"]},
              {"r":"~2", "i":["kodayante"]}]},
        {"f":["kodayase"],
         "v":"kudf!",
         "s":"TAs",
         "n":"10.0008",
         "p":"u",
         "l":"law",
         "d":[{"r":"1.3.1", "i":["kudf!"]},
              {"r":"1.3.2", "i":["kudf!"]},
              {"r":"1.3.9", "i":["kud"]},
              {"r":"3.1.32", "i":["kud"]},
              {"r":"3.4.69", "i":["kud"]},
              {"r":"3.2.123", "i":["kud+la!w"]},
              {"r":"3.4.77", "i":["kud+la!w"]},
              {"r":"1.3.3", "i":["kud+la!w"]},
              {"r":"1.3.9", "i":["kud+la!"]},
              {"r":"1.3.2", "i":["kud+la!"]},
              {"r":"1.3.9", "i":["kud+l"]},
              {"r":"3.4.78", "i":["kud+TAs"]},
              {"r":"1.4.100", "i":["kud+TAs"]},
              {"r":"1.4.101", "i":["kud+TAs"]},
              {"r":"1.4.102", "i":["kud+TAs"]},
              {"r":"1.4.105", "i":["kud+TAs"]},
              {"r":"3.4.113", "i":["kud+TAs"]},
              {"r":"3.1.25", "i":["kud+Ric+TAs"]},
              {"r":"3.1.68", "i":["kud+Ric+Sap+TAs"]},
              {"r":"3.4.113", "i":["kud+Ric+Sap+TAs"]},
              {"r":"1.3.8", "i":["kud+Ric+Sap+TAs"]},
              {"r":"1.3.3", "i":["kud+Ric+Sap+TAs"]},
              {"r":"1.3.7", "i":["kud+Ric+Sap+TAs"]},
              {"r":"1.3.9", "i":["kud+i+a+TAs"]},
              {"r":"7.3.86", "i":["kodi+a+TAs"]},
              {"r":"1.3.4", "i":["kodi+a+TAs"]},
              {"r":"3.4.80", "i":["kodi+a+se"]},
              {"r":"7.3.84", "i":["kode+a+se"]},
              {"r":"6.1.78", "i":["koday+a+se"]},
              {"r":"~2", "i":["kodayase"]}]},
        {"f":["kodayeTe"],
         "v":"kudf!",
         "s":"ATAm",
         "n":"10.0008",
         "p":"u",
         "l":"law",
         "d":[{"r":"1.3.1", "i":["kudf!"]},
              {"r":"1.3.2", "i":["kudf!"]},
              {"r":"1.3.9", "i":["kud"]},
              {"r":"3.1.32", "i":["kud"]},
              {"r":"3.4.69", "i":["kud"]},
              {"r":"3.2.123", "i":["kud+la!w"]},
              {"r":"3.4.77", "i":["kud+la!w"]},
              {"r":"1.3.3", "i":["kud+la!w"]},
              {"r":"1.3.9", "i":["kud+la!"]},
              {"r":"1.3.2", "i":["kud+la!"]},
              {"r":"1.3.9", "i":["kud+l"]},
              {"r":"3.4.78", "i":["kud+ATAm"]},
              {"r":"1.4.100", "i":["kud+ATAm"]},
              {"r":"1.4.101", "i":["kud+ATAm"]},
              {"r":"1.4.102", "i":["kud+ATAm"]},
              {"r":"1.4.105", "i":["kud+ATAm"]},
              {"r":"3.4.113", "i":["kud+ATAm"]},
              {"r":"3.1.25", "i":["kud+Ric+ATAm"]},
              {"r":"3.1.68", "i":["kud+Ric+Sap+ATAm"]},
              {"r":"3.4.113", "i":["kud+Ric+Sap+ATAm"]},
              {"r":"1.3.8", "i":["kud+Ric+Sap+ATAm"]},
              {"r":"1.3.3", "i":["kud+Ric+Sap+ATAm"]},
              {"r":"1.3.7", "i":["kud+Ric+Sap+ATAm"]},
              {"r":"1.3.9", "i":["kud+i+a+ATAm"]},
              {"r":"7.3.86", "i":["kodi+a+ATAm"]},
              {"r":"1.3.4", "i":["kodi+a+ATAm"]},
              {"r":"3.4.79", "i":["kodi+a+ATe"]},
              {"r":"7.2.81", "i":["kodi+a+iy+Te"]},
              {"r":"7.3.84", "i":["kode+a+iy+Te"]},
              {"r":"6.1.78", "i":["koday+a+iy+Te"]},
              {"r":"6.1.66", "i":["koday+a+i+Te"]},
              {"r":"6.1.87", "i":["koday+eTe"]},
              {"r":"~2", "i":["kodayeTe"]}]},
        {"f":["kodayaDve"],
         "v":"kudf!",
         "s":"Dvam",
         "n":"10.0008",
         "p":"u",
         "l":"law",
         "d":[{"r":"1.3.1", "i":["kudf!"]},
              {"r":"1.3.2", "i":["kudf!"]},
              {"r":"1.3.9", "i":["kud"]},
              {"r":"3.1.32", "i":["kud"]},
              {"r":"3.4.69", "i":["kud"]},
              {"r":"3.2.123", "i":["kud+la!w"]},
              {"r":"3.4.77", "i":["kud+la!w"]},
              {"r":"1.3.3", "i":["kud+la!w"]},
              {"r":"1.3.9", "i":["kud+la!"]},
              {"r":"1.3.2", "i":["kud+la!"]},
              {"r":"1.3.9", "i":["kud+l"]},
              {"r":"3.4.78", "i":["kud+Dvam"]},
              {"r":"1.4.100", "i":["kud+Dvam"]},
              {"r":"1.4.101", "i":["kud+Dvam"]},
              {"r":"1.4.102", "i":["kud+Dvam"]},
              {"r":"1.4.105", "i":["kud+Dvam"]},
              {"r":"3.4.113", "i":["kud+Dvam"]},
              {"r":"3.1.25", "i":["kud+Ric+Dvam"]},
              {"r":"3.1.68", "i":["kud+Ric+Sap+Dvam"]},
              {"r":"3.4.113", "i":["kud+Ric+Sap+Dvam"]},
              {"r":"1.3.8", "i":["kud+Ric+Sap+Dvam"]},
              {"r":"1.3.3", "i":["kud+Ric+Sap+Dvam"]},
              {"r":"1.3.7", "i":["kud+Ric+Sap+Dvam"]},
              {"r":"1.3.9", "i":["kud+i+a+Dvam"]},
              {"r":"7.3.86", "i":["kodi+a+Dvam"]},
              {"r":"1.3.4", "i":["kodi+a+Dvam"]},
              {"r":"3.4.79", "i":["kodi+a+Dve"]},
              {"r":"7.3.84", "i":["kode+a+Dve"]},
              {"r":"6.1.78", "i":["koday+a+Dve"]},
              {"r":"~2", "i":["kodayaDve"]}]},
        {"f":["kodaye"],
         "v":"kudf!",
         "s":"iw",
         "n":"10.0008",
         "p":"u",
         "l":"law",
         "d":[{"r":"1.3.1", "i":["kudf!"]},
              {"r":"1.3.2", "i":["kudf!"]},
              {"r":"1.3.9", "i":["kud"]},
              {"r":"3.1.32", "i":["kud"]},
              {"r":"3.4.69", "i":["kud"]},
              {"r":"3.2.123", "i":["kud+la!w"]},
              {"r":"3.4.77", "i":["kud+la!w"]},
              {"r":"1.3.3", "i":["kud+la!w"]},
              {"r":"1.3.9", "i":["kud+la!"]},
              {"r":"1.3.2", "i":["kud+la!"]},
              {"r":"1.3.9", "i":["kud+l"]},
              {"r":"3.4.78", "i":["kud+iw"]},
              {"r":"1.4.100", "i":["kud+iw"]},
              {"r":"1.4.101", "i":["kud+iw"]},
              {"r":"1.4.102", "i":["kud+iw"]},
              {"r":"1.4.107", "i":["kud+iw"]},
              {"r":"3.4.113", "i":["kud+iw"]},
              {"r":"3.1.25", "i":["kud+Ric+iw"]},
              {"r":"3.1.68", "i":["kud+Ric+Sap+iw"]},
              {"r":"3.4.113", "i":["kud+Ric+Sap+iw"]},
              {"r":"1.3.8", "i":["kud+Ric+Sap+iw"]},
              {"r":"1.3.3", "i":["kud+Ric+Sap+iw"]},
              {"r":"1.3.7", "i":["kud+Ric+Sap+iw"]},
              {"r":"1.3.9", "i":["kud+i+a+iw"]},
              {"r":"7.3.86", "i":["kodi+a+iw"]},
              {"r":"1.3.3", "i":["kodi+a+iw"]},
              {"r":"1.3.9", "i":["kodi+a+i"]},
              {"r":"3.4.79", "i":["kodi+a+e"]},
              {"r":"7.3.84", "i":["kode+a+e"]},
              {"r":"6.1.78", "i":["koday+a+e"]},
              {"r":"6.1.97", "i":["koday+e"]},
              {"r":"~2", "i":["kodaye"]}]},
        {"f":["kodayAvahe"],
         "v":"kudf!",
         "s":"vahi",
         "n":"10.0008",
         "p":"u",
         "l":"law",
         "d":[{"r":"1.3.1", "i":["kudf!"]},
              {"r":"1.3.2", "i":["kudf!"]},
              {"r":"1.3.9", "i":["kud"]},
              {"r":"3.1.32", "i":["kud"]},
              {"r":"3.4.69", "i":["kud"]},
              {"r":"3.2.123", "i":["kud+la!w"]},
              {"r":"3.4.77", "i":["kud+la!w"]},
              {"r":"1.3.3", "i":["kud+la!w"]},
              {"r":"1.3.9", "i":["kud+la!"]},
              {"r":"1.3.2", "i":["kud+la!"]},
              {"r":"1.3.9", "i":["kud+l"]},
              {"r":"3.4.78", "i":["kud+vahi"]},
              {"r":"1.4.100", "i":["kud+vahi"]},
              {"r":"1.4.101", "i":["kud+vahi"]},
              {"r":"1.4.102", "i":["kud+vahi"]},
              {"r":"1.4.107", "i":["kud+vahi"]},
              {"r":"3.4.113", "i":["kud+vahi"]},
              {"r":"3.1.25", "i":["kud+Ric+vahi"]},
              {"r":"3.1.68", "i":["kud+Ric+Sap+vahi"]},
              {"r":"3.4.113", "i":["kud+Ric+Sap+vahi"]},
              {"r":"1.3.8", "i":["kud+Ric+Sap+vahi"]},
              {"r":"1.3.3", "i":["kud+Ric+Sap+vahi"]},
              {"r":"1.3.7", "i":["kud+Ric+Sap+vahi"]},
              {"r":"1.3.9", "i":["kud+i+a+vahi"]},
              {"r":"7.3.86", "i":["kodi+a+vahi"]},
              {"r":"3.4.79", "i":["kodi+a+vahe"]},
              {"r":"7.3.84", "i":["kode+a+vahe"]},
              {"r":"6.1.78", "i":["koday+a+vahe"]},
              {"r":"7.3.101", "i":["kodayA+vahe"]},
              {"r":"~2", "i":["kodayAvahe"]}]},
        {"f":["kodayAmahe"],
         "v":"kudf!",
         "s":"mahiN",
         "n":"10.0008",
         "p":"u",
         "l":"law",
         "d":[{"r":"1.3.1", "i":["kudf!"]},
              {"r":"1.3.2", "i":["kudf!"]},
              {"r":"1.3.9", "i":["kud"]},
              {"r":"3.1.32", "i":["kud"]},
              {"r":"3.4.69", "i":["kud"]},
              {"r":"3.2.123", "i":["kud+la!w"]},
              {"r":"3.4.77", "i":["kud+la!w"]},
              {"r":"1.3.3", "i":["kud+la!w"]},
              {"r":"1.3.9", "i":["kud+la!"]},
              {"r":"1.3.2", "i":["kud+la!"]},
              {"r":"1.3.9", "i":["kud+l"]},
              {"r":"3.4.78", "i":["kud+mahiN"]},
              {"r":"1.4.100", "i":["kud+mahiN"]},
              {"r":"1.4.101", "i":["kud+mahiN"]},
              {"r":"1.4.102", "i":["kud+mahiN"]},
              {"r":"1.4.107", "i":["kud+mahiN"]},
              {"r":"3.4.113", "i":["kud+mahiN"]},
              {"r":"3.1.25", "i":["kud+Ric+mahiN"]},
              {"r":"3.1.68", "i":["kud+Ric+Sap+mahiN"]},
              {"r":"3.4.113", "i":["kud+Ric+Sap+mahiN"]},
              {"r":"1.3.8", "i":["kud+Ric+Sap+mahiN"]},
              {"r":"1.3.3", "i":["kud+Ric+Sap+mahiN"]},
              {"r":"1.3.7", "i":["kud+Ric+Sap+mahiN"]},
              {"r":"1.3.9", "i":["kud+i+a+mahiN"]},
              {"r":"7.3.86", "i":["kodi+a+mahiN"]},
              {"r":"1.3.3", "i":["kodi+a+mahiN"]},
              {"r":"1.3.9", "i":["kodi+a+mahi"]},
              {"r":"3.4.79", "i":["kodi+a+mahe"]},
              {"r":"7.3.84", "i":["kode+a+mahe"]},
              {"r":"6.1.78", "i":["koday+a+mahe"]},
              {"r":"7.3.101", "i":["kodayA+mahe"]},
              {"r":"~2", "i":["kodayAmahe"]}]}
]

module.exports = data;

}, {}]}, {}, {"1":""})